#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config focus_follows_pointer true

# Window borders (Auto-Generate)
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config border_width 3
bspc config borderless_monocle true

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"
bspc rule -a "archmenu.py" state=floating layer=above focus=true
bspc rule -a "network.py" state=floating layer=above focus=true

# fix pointer
xsetroot -cursor_name left_ptr

# gaps
bspc config gapless_monocle false
bspc config window_gap 10

# moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# rules
bspc rule -a feh state=floating

# start resources
xrdb merge ~/.Xresources

# touchpad changes
touchpad_id=$(xinput list | grep -i touchpad | sed 's/.*id=\([0-9]\+\).*/\1/')
xinput set-prop $touchpad_id "libinput Natural Scrolling Enabled" 1
xinput set-prop $touchpad_id "libinput Tapping Enabled" 1

# launch battery tracker and redshift
$HOME/bin/battery-alert &
pgrep -x redshift > /dev/null || redshift &	

# set wallpaper
feh --bg-fill $HOME/Pictures/wallpapers/arch.jpg

# set volume 0%
amixer -q set Master 0%

# toggle polybar from start
sh $HOME/.config/polybar/toggle-polybar

# start compositor
picom --config $HOME/.config/bspwm/picom_conf/1.conf &

# launch notifications
dunst &

